development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: emma
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: emma
  password: password1